# filepath: /c:/Users/Justin-PC/Desktop/UB/ojt-time-tracker/backend/config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ub-qaoms
  password: password
  host: localhost

development:
  <<: *default
  database: ojt_time_tracker_development

test:
  <<: *default
  database: ojt_time_tracker_test

production:
  <<: *default
  database: ojt_time_tracker_production
  username: ub-qaoms
  password: password