# This file is automatically generated by ActiveRecord and should not be edited manually. 

ActiveRecord::SchemaDumper.dump ActiveRecord::Base.connection, File.open('db/schema.rb', 'w') do |f|
  f.write <<-RUBY
ActiveRecord::Schema.define(version: 2023_10_01_000001) do

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
  end

end
  RUBY
end